# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: synFireCloud 的个人网站
email: 15687127573@163.com
description: >
baseurl: ""
url: "http://synfirecloud.github.io/" # the base hostname & protocol for your site
github_username:  synFireCloud

# Build settings
markdown: kramdown
